# Generated by Django 5.0.3 on 2024-07-01 15:30

import api.models
import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Required. First name', max_length=150, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(code='invalid_first_name', message='First name must contain only letters', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Required. Last name', max_length=150, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(code='invalid_first_name', message='First name must contain only letters', regex='^[a-zA-Z]+$')]),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Required. Group's name", max_length=150, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(code='invalid_group_name', message='Group name must contain only letters', regex='^[a-zA-Z]+$')])),
                ('image', models.ImageField(default='/defaults/group-default.png', upload_to=api.models.Group.upload_to)),
                ('members', models.ManyToManyField(related_name='note_groups', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='owned_note_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
