# Generated by Django 5.0.3 on 2024-07-01 18:02

import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_first_name_alter_user_last_name_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='note_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text="Required. Group's name", max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_note_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Required. Note's title", max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('content', models.TextField(help_text='Content of the note. Includes CodeBlock.')),
                ('members', models.ManyToManyField(blank=True, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, related_name='owned_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
