# Generated by Django 5.0.3 on 2024-07-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_group_members_alter_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='htmlCode',
            field=models.TextField(default='<h1>Hello</h1>', help_text='HTML content of the note. Includes CodeBlock.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='nativeCode',
            field=models.TextField(default='<Text>Hello</Text>', help_text='Native content of the note. Includes CodeBlock.'),
            preserve_default=False,
        ),
    ]
