# Generated by Django 5.0.3 on 2024-07-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_note_content_note_htmlcode_note_nativecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='htmlCode',
            field=models.TextField(default='', help_text='HTML content of the note. Includes CodeBlock.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='nativeCode',
            field=models.TextField(default='', help_text='Native content of the note. Includes CodeBlock.'),
        ),
    ]
