# Generated by Django 5.0.3 on 2024-07-07 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_note_htmlcode_alter_note_nativecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(related_name='related_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
