# Generated by Django 5.0.3 on 2024-07-07 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sent_at', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='contact_requests_received',
            field=models.ManyToManyField(related_name='contact_requests_received', to='api.contactrequest'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_requests_sent',
            field=models.ManyToManyField(related_name='contact_requests_sent', to='api.contactrequest'),
        ),
    ]
