# Generated by Django 5.0.3 on 2024-07-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactrequest_user_contact_requests_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_requests_received',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_requests_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
    ]
