# Generated by Django 5.0.3 on 2024-07-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_contactrequest_sent_at_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRequest',
            new_name='Invitation',
        ),
    ]
